# Build the tester package: the jar plus the docs a tester needs, in one folder and one zip.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\spike\work\make_tester_package.ps1
#
# Why every path is DISCOVERED instead of written down: Windows PowerShell 5.1 parses a .ps1 in the ANSI code
# page unless it carries a UTF-8 BOM, and the real names here are Chinese (mods/<name>-<version>-<suffix>,
# docs/<reference>.docx). An earlier version of this script hard-coded them and simply would not parse
# ("Missing closing ')' in expression" on an innocent if-statement). So this file is pure ASCII and finds the
# existing names by globbing, which also means a renamed package keeps working.
#
# Why it checks timestamps: the .docx is a BUILD ARTIFACT of docs/COMMAND_AND_CONFIG_REFERENCE.md (generated by
# tools/make_reference_docx.js, finished by tools/spike/work/docx_finalize.ps1). Shipping a docx older than the
# markdown it was made from is exactly how a tester ends up reading a table that no longer matches the jar, so
# this script refuses instead of copying a stale one.
param(
    [string]$Root = 'D:\deepseek\ArmedMobs',
    [string]$Version = '0.1.0',
    [string]$JarName = '',
    [switch]$SkipDocxFreshnessCheck
)
$ErrorActionPreference = 'Stop'

$mods = Join-Path $Root 'mods'
if (-not $JarName) { $JarName = "armedmobs-$Version-all.jar" }
$jar = Join-Path $Root "build\libs\$JarName"
$referenceMd = Join-Path $Root 'docs\COMMAND_AND_CONFIG_REFERENCE.md'

# ---- the Chinese names, discovered
$referenceDocx = (Get-ChildItem -LiteralPath (Join-Path $Root 'docs') -Filter '*.docx' |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
$install = (Get-ChildItem -LiteralPath $mods -Filter '*.txt' | Select-Object -First 1).FullName
$modsMd = (Get-ChildItem -LiteralPath $mods -Filter '*.md' | Select-Object -First 1).FullName
$existing = Get-ChildItem -LiteralPath $mods -Directory | Where-Object { $_.Name -like "*$Version*" } |
    Select-Object -First 1
if (-not $existing) {
    throw "cannot find an existing mods/<name>-$Version-<suffix> folder to take the package name from"
}
$packageName = $existing.Name
$packageDir = Join-Path $mods $packageName
$zip = Join-Path $mods "$packageName.zip"

foreach ($required in @($jar, $referenceMd, $referenceDocx, $install, $modsMd)) {
    if (-not $required -or -not (Test-Path -LiteralPath $required)) { throw "missing: $required" }
}

# ---------------------------------------------------------------- 1. is the docx newer than its source?
$mdTime = (Get-Item -LiteralPath $referenceMd).LastWriteTimeUtc
$docxTime = (Get-Item -LiteralPath $referenceDocx).LastWriteTimeUtc
Write-Host ("reference.md   {0:yyyy-MM-dd HH:mm:ss}Z" -f $mdTime)
Write-Host ("reference.docx {0:yyyy-MM-dd HH:mm:ss}Z" -f $docxTime)
if ($docxTime -lt $mdTime -and -not $SkipDocxFreshnessCheck) {
    # Plain statements, not a multi-line string concatenation: this shell's parser rejects an expression whose
    # continuation line starts with an operator ("Missing closing ')' in expression"), which is a trap worth
    # not stepping in twice.
    $stale = 'the .docx is OLDER than the markdown it is generated from - regenerate it first:'
    $stale = $stale + ' node tools/make_reference_docx.js, then tools/spike/work/docx_finalize.ps1'
    $stale = $stale + ' (or pass -SkipDocxFreshnessCheck to ship it anyway, which a tester will notice)'
    throw $stale
}

# ---------------------------------------------------------------- 2. the sha, written down
$sha = (Get-FileHash -LiteralPath $jar -Algorithm SHA256).Hash.ToLower()
$size = (Get-Item -LiteralPath $jar).Length
Set-Content -Path (Join-Path $mods 'SHA256SUMS') -Value "$sha  $JarName`n" -NoNewline -Encoding ascii

# ---------------------------------------------------------------- 3. the folder
if (Test-Path -LiteralPath $packageDir) { Remove-Item -LiteralPath $packageDir -Recurse -Force }
New-Item -ItemType Directory -Path $packageDir | Out-Null
Copy-Item -LiteralPath $jar -Destination (Join-Path $packageDir $JarName)
Copy-Item -LiteralPath (Join-Path $mods 'SHA256SUMS') -Destination $packageDir
Copy-Item -LiteralPath $install -Destination $packageDir
Copy-Item -LiteralPath $referenceDocx -Destination $packageDir
Copy-Item -LiteralPath $referenceMd -Destination (Join-Path $packageDir (Split-Path $modsMd -Leaf))
Get-ChildItem -LiteralPath $packageDir | ForEach-Object {
    Write-Host ("  {0,-40} {1,10} bytes" -f $_.Name, $_.Length)
}

# ---------------------------------------------------------------- 4. the zip, read back
if (Test-Path -LiteralPath $zip) { Remove-Item -LiteralPath $zip -Force }
Compress-Archive -Path (Join-Path $packageDir '*') -DestinationPath $zip -CompressionLevel Optimal
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [IO.Compression.ZipFile]::OpenRead($zip)
try {
    $entries = $archive.Entries
    Write-Host ("zip: {0}  {1} entries  {2} bytes  sha256 {3}" -f `
        (Split-Path $zip -Leaf), $entries.Count, (Get-Item $zip).Length,
        (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash.ToLower())
    foreach ($entry in $entries) { Write-Host ("  {0,-40} {1,10} bytes" -f $entry.FullName, $entry.Length) }
    if ($entries.Count -lt 3) { throw 'the zip has fewer than three entries - packaging went wrong' }
} finally {
    $archive.Dispose()
}
Write-Host ''
Write-Host "package: $packageDir"
Write-Host "zip    : $zip"
Write-Host "jar    : $JarName  $size bytes  sha256 $sha"
