# Build the tester package: the jar plus the docs a tester needs, in one folder and one zip.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\spike\work\make_tester_package.ps1
#
# Why every path is DISCOVERED instead of written down: Windows PowerShell 5.1 parses a .ps1 in the ANSI code
# page unless it carries a UTF-8 BOM, and the real names here are Chinese (mods/<name>-<version>-<suffix>,
# build/docs/<reference>.docx). An earlier version of this script hard-coded them and simply would not parse
# ("Missing closing ')' in expression" on an innocent if-statement). So this file is pure ASCII and finds the
# existing names by globbing, which also means a renamed package keeps working.
#
# Why it checks timestamps: the .docx is a BUILD ARTIFACT of docs/COMMAND_AND_CONFIG_REFERENCE.md (generated by
# tools/make_reference_docx.js, finished by tools/spike/work/docx_finalize.ps1). Shipping a docx older than the
# markdown it was made from is exactly how a tester ends up reading a table that no longer matches the jar, so
# this script refuses instead of copying a stale one.
param(
    [string]$Root = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path,
    [string]$Version = '0.1.0',
    [string]$JarName = '',
    [string]$PackageName = '',
    [switch]$IncludeGeckoLib,
    [switch]$SkipDocxFreshnessCheck
)
$ErrorActionPreference = 'Stop'
$Root = (Resolve-Path -LiteralPath $Root).Path

$mods = Join-Path $Root 'mods'
if (-not $JarName) {
    $JarName = if ($IncludeGeckoLib) { "armedmobs-$Version-all.jar" } else { "armedmobs-$Version.jar" }
}
$jar = Join-Path $Root "build\libs\$JarName"
$referenceMd = Join-Path $Root 'docs\COMMAND_AND_CONFIG_REFERENCE.md'

# ---- the Chinese names, discovered
$referenceDocx = (Get-ChildItem -LiteralPath (Join-Path $Root 'build\docs') -Filter '*.docx' -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1).FullName
$install = (Get-ChildItem -LiteralPath $mods -Filter '*.txt' | Select-Object -First 1).FullName
if (-not $PackageName) { $PackageName = "armedmobs-$Version-test" }
$packageRoot = [IO.Path]::GetFullPath((Join-Path $Root 'build\packages')).TrimEnd('\', '/')
$packageDir = [IO.Path]::GetFullPath((Join-Path $packageRoot $PackageName))
$zip = [IO.Path]::GetFullPath((Join-Path $packageRoot "$PackageName.zip"))
foreach ($outputPath in @($packageDir, $zip)) {
    if (-not $outputPath.StartsWith($packageRoot + [IO.Path]::DirectorySeparatorChar,
            [StringComparison]::OrdinalIgnoreCase)) {
        throw "package output must stay within $packageRoot : $outputPath"
    }
}

foreach ($required in @($jar, $referenceMd, $referenceDocx, $install)) {
    if (-not $required -or -not (Test-Path -LiteralPath $required)) { throw "missing: $required" }
}

# ---------------------------------------------------------------- 1. is the docx newer than its source?
$mdTime = (Get-Item -LiteralPath $referenceMd).LastWriteTimeUtc
$docxTime = (Get-Item -LiteralPath $referenceDocx).LastWriteTimeUtc
Write-Host ("reference.md   {0:yyyy-MM-dd HH:mm:ss}Z" -f $mdTime)
Write-Host ("reference.docx {0:yyyy-MM-dd HH:mm:ss}Z" -f $docxTime)
if ($docxTime -lt $mdTime -and -not $SkipDocxFreshnessCheck) {
    # Plain statements, not a multi-line string concatenation: this shell's parser rejects an expression whose
    # continuation line starts with an operator ("Missing closing ')' in expression"), which is a trap worth
    # not stepping in twice.
    $stale = 'the .docx is OLDER than the markdown it is generated from - regenerate it first:'
    $stale = $stale + ' node tools/make_reference_docx.js, then tools/spike/work/docx_finalize.ps1'
    $stale = $stale + ' (or pass -SkipDocxFreshnessCheck to ship it anyway, which a tester will notice)'
    throw $stale
}

# ---------------------------------------------------------------- 2. the sha, written down
$sha = (Get-FileHash -LiteralPath $jar -Algorithm SHA256).Hash.ToLower()
$size = (Get-Item -LiteralPath $jar).Length
New-Item -ItemType Directory -Force -Path $packageRoot | Out-Null
$checksumFile = Join-Path $packageRoot 'SHA256SUMS'
Set-Content -LiteralPath $checksumFile -Value "$sha  $JarName`n" -NoNewline -Encoding ascii

# ---------------------------------------------------------------- 3. the folder
if (Test-Path -LiteralPath $packageDir) { Remove-Item -LiteralPath $packageDir -Recurse -Force }
New-Item -ItemType Directory -Path $packageDir | Out-Null
Copy-Item -LiteralPath $jar -Destination (Join-Path $packageDir $JarName)
Copy-Item -LiteralPath $checksumFile -Destination $packageDir
Copy-Item -LiteralPath $install -Destination $packageDir
Copy-Item -LiteralPath $referenceDocx -Destination $packageDir
Copy-Item -LiteralPath $referenceMd -Destination (Join-Path $packageDir (([IO.Path]::GetFileNameWithoutExtension($referenceDocx)) + '.md'))
$dependencyNote = if ($JarName -like '*-all.jar') {
    'This JAR includes GeckoLib; do not also install the ordinary Armed Mobs JAR.'
} else {
    'This JAR does not include GeckoLib. Install GeckoLib for Forge 1.20.1 separately (development uses 4.8.4). Do not also install the Armed Mobs -all JAR.'
}
Set-Content -LiteralPath (Join-Path $packageDir 'DEPENDENCIES.txt') -Encoding ascii -Value @(
    'Minecraft 1.20.1 / Forge 47.x',
    $dependencyNote,
    'TaCZ 1.1.7+ is optional. Install it on both sides for firearms; without it, units use vanilla bows/crossbows.'
)
Get-ChildItem -LiteralPath $packageDir | ForEach-Object {
    Write-Host ("  {0,-40} {1,10} bytes" -f $_.Name, $_.Length)
}

# ---------------------------------------------------------------- 4. the zip, read back
if (Test-Path -LiteralPath $zip) { Remove-Item -LiteralPath $zip -Force }
Compress-Archive -Path (Join-Path $packageDir '*') -DestinationPath $zip -CompressionLevel Optimal
Add-Type -AssemblyName System.IO.Compression.FileSystem
$archive = [IO.Compression.ZipFile]::OpenRead($zip)
try {
    $entries = $archive.Entries
    Write-Host ("zip: {0}  {1} entries  {2} bytes  sha256 {3}" -f `
        (Split-Path $zip -Leaf), $entries.Count, (Get-Item $zip).Length,
        (Get-FileHash -LiteralPath $zip -Algorithm SHA256).Hash.ToLower())
    foreach ($entry in $entries) { Write-Host ("  {0,-40} {1,10} bytes" -f $entry.FullName, $entry.Length) }
    if ($entries.Count -lt 3) { throw 'the zip has fewer than three entries - packaging went wrong' }
} finally {
    $archive.Dispose()
}
Write-Host ''
Write-Host "package: $packageDir"
Write-Host "zip    : $zip"
Write-Host "jar    : $JarName  $size bytes  sha256 $sha"
