# Phase B generator: for each showroom site emit the pad (fill stone body + smooth_stone top),
# the air clearance above it, and the structure placement.
#
# The city template tarkovscav:city_small is 48x26x48 (local y=0 is a solid 48x48 coarse_dirt lot),
# and /place template maps local (0,0,0) to exactly the given pos, for every rotation and mirror
# (StructureTemplate.getZeroPositionWithTransform always re-anchors the rotated box on pos).
# So a copy requested at (x, y, z) occupies x..x+47, z..z+47, y..y+25 - which is what the
# coordinate table in the docs claims.
param(
    [string]$WorkDir = 'D:\deepseek\ArmedMobs\tools\spike\citysave'
)

$ErrorActionPreference = 'Stop'

# padTop = the lowest of the five surface probes for that site (measured in 02-probe.txt), so the pad
# is cut down to the local plain instead of floating above it.
$CLEAR_TOP = 150
$sites = @(
    @{ id = 1; name = 'city1-original';      ox = 40;  oz = 120; padTop = 63; pad = 64; extra = 'origin' },
    @{ id = 2; name = 'city2-cw90';          ox = 200; oz = 120; padTop = 63; pad = 64; extra = 'origin' },
    @{ id = 3; name = 'city3-180';           ox = 360; oz = 120; padTop = 63; pad = 64; extra = 'origin' },
    @{ id = 4; name = 'city4-ccw90';         ox = 520; oz = 120; padTop = 63; pad = 64; extra = 'origin' },
    @{ id = 5; name = 'city5-mirror-lr';     ox = 40;  oz = 320; padTop = 89; pad = 64; extra = 'origin' },
    @{ id = 6; name = 'city6-mirror-fb-cw90';ox = 200; oz = 320; padTop = 63; pad = 64; extra = 'origin' },
    # /place structure picks a random x/z inside the chunk it is given, so this pad is offset and
    # oversized (80x80) to contain every origin the chunk (384..399, 336..351) can produce.
    @{ id = 7; name = 'city7-place-structure'; ox = 375; oz = 327; padTop = 63; pad = 80; extra = 'worldgen' }
)

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add('# generated by build-city.ps1')

function Add-Fill([int]$x1, [int]$z1, [int]$x2, [int]$z2, [int]$yFrom, [int]$yTo, [string]$block) {
    # vanilla /fill caps out at 32768 blocks; a 64x64 layer is 4096, so 8 layers per command.
    $layers = $yTo - $yFrom + 1
    $span = [Math]::Floor(32768 / (($x2 - $x1 + 1) * ($z2 - $z1 + 1)))
    if ($span -lt 1) { $span = 1 }
    $y = $yFrom
    while ($y -le $yTo) {
        $end = [Math]::Min($y + $span - 1, $yTo)
        $lines.Add("fill $x1 $y $z1 $x2 $end $z2 $block")
        $y = $end + 1
    }
}

foreach ($s in $sites) {
    $ox = $s.ox; $oz = $s.oz; $pt = $s.padTop; $pad = $s.pad
    $half0 = 0; $half1 = $pad - 1
    $x1 = $ox - 8; $z1 = $oz - 8
    $x2 = $x1 + $pad - 1; $z2 = $z1 + $pad - 1
    $lines.Add("# ---- site $($s.id) $($s.name): pad $pad x $pad at x $x1..$x2 z $z1..$z2, padTop=$pt ----")
    $lines.Add("forceload add $x1 $z1 $x2 $z2")
    Add-Fill $x1 $z1 $x2 $z2 ($pt - 8) ($pt - 1) 'minecraft:stone'
    Add-Fill $x1 $z1 $x2 $z2 $pt $pt 'minecraft:smooth_stone'
    Add-Fill $x1 $z1 $x2 $z2 ($pt + 1) $CLEAR_TOP 'minecraft:air'
}

$lines.Add('# ---- placements ----')
$lines.Add('place template tarkovscav:city_small 40 63 120')
$lines.Add('place template tarkovscav:city_small 200 63 120 clockwise_90')
$lines.Add('place template tarkovscav:city_small 360 63 120 180')
$lines.Add('place template tarkovscav:city_small 520 63 120 counterclockwise_90')
$lines.Add('place template tarkovscav:city_small 40 89 320 none left_right')
$lines.Add('place template tarkovscav:city_small 200 63 320 clockwise_90 front_back')
$lines.Add('# worldgen route: origin lands somewhere inside chunk x 384..399, z 336..351')
$lines.Add('place structure tarkovscav:city_small 384 63 336')

$batch = Join-Path $WorkDir 'batches\10-build.txt'
[System.IO.File]::WriteAllLines($batch, $lines, (New-Object System.Text.UTF8Encoding($false)))
Write-Output "wrote $($lines.Count) commands to $batch"
